version: '3'
services:
  docusaurus:
    image: node:20-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm run build && npm run serve --host 0.0.0.0"
    ports:
      - 3000:3000
