name: "docusaurus"
services:
    dev:
        build:
            context: .
            target: dev
        ports:
            - "3000:3000"
        volumes:
            - .:/home/docker/docusaurus
        environment:
            - NODE_ENV=development